### PR TITLE
arbitrary change for the preview

### PR DESCRIPTION
**Pull request by carriewright11**
preview on branch wasn't looking up-to-date for docx version... trying a new branch

### CODE REVIEW

**Comment by carriewright11** [comment]
@cansavvy  the docx file doesn't appear to be updated - any advice?

**Comment by cansavvy** [comment]
> @cansavvy the docx file doesn't appear to be updated - any advice?

Can you tell me what changes you are looking for that you don't see? This might help me get to the bottom of this.

**Comment by carriewright11** [comment]
> Can you tell me what changes you are looking for that you don't see? This might help me get to the bottom of this.

The tips for my section - if you search for "tips for" should be separated by decision makers for users and decision makers for development. Also there should not be a chapter in my course about testing and training data

**Comment by carriewright11** [comment]
Closing this since I made an issue about this

**Pull request closed without merging**
